<?php 
sleep(2);
	$arr = array(
		'status'=>200,
		'data'=>array(
			array(
				'name'=>'lcafwwwwwwwwwwwwwwwwwwwww',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			),
			array(
				'name'=>'lc',
				'xueyuan'=>'软件',
				'rank'=>100
			)
		)
	);
	echo json_encode($arr);
 ?>